<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Twm.Application/Twm.Application.csproj" />
    <ProjectReference Include="../Twm.Presentation/Twm.Presentation.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
