<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>

  <!-- Shared test infrastructure. -->
  <ItemGroup>
    <ProjectReference Include="../../src/Twm.Application/Twm.Application.csproj" />
    <ProjectReference Include="../../src/Twm.Domain/Twm.Domain.csproj" />
  </ItemGroup>
</Project>
