<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>twm-msg</AssemblyName>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Twm.Shared.Ipc\Twm.Shared.Ipc.csproj" />
  </ItemGroup>
</Project>
