<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Twm.Core/Twm.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="VYaml" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Twm.Platform.Tests" />
  </ItemGroup>
</Project>
