<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Twm.Application\Twm.Application.csproj" />
    <ProjectReference Include="..\Twm.Shared.Ipc\Twm.Shared.Ipc.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
</Project>
