<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Twm.Application\Twm.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="VYaml" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Twm.Adapters.Config.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
</Project>
