name: SonarQube Scan
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  scan:
    name: SonarQube
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup - DotNet
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          global-json-file: global.json
      - name: Scan - SonarQube Server
        id: sonar
        uses: mammothb/sonarqube-ce@4eeed9a307bfa62ab70b812659cebefa946545a6 # v1.2.0
        with:
          scan-mode: 'none'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          generate-pr-comment: true
          new-code-n-days: "3d"
          reports-scopes: '["overall", "new"]'
          reports-retention-days: "7"
      - name: Setup - SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Scan
        env:
          SONAR_HOST_URL: ${{ steps.sonar.outputs.sonar-host-url }}
          SONAR_TOKEN: ${{ steps.sonar.outputs.sonar-token }}
        run: |
          dotnet sonarscanner begin \
            /k:"${{ steps.sonar.outputs.sonar-project-key }}" \
            /d:sonar.host.url="${SONAR_HOST_URL}" \
            /d:sonar.token="${SONAR_TOKEN}"

          make coverage

          dotnet sonarscanner end \
            /d:sonar.token="${SONAR_TOKEN}"
